version: '3.7'

services:
  pocketbase:
    image: pocketbase:latest
    container_name: pocketbase_container
    ports:
      - "8090:8090"
    volumes:
      - pocketbase_data:/pb/pb_data
    restart: always

volumes:
  pocketbase_data:
