version: '3.7'

services:
  pocketbase:
    build: .
    container_name: pocketbase_container
    ports:
      - "10000:8090"
    volumes:
      - pocketbase_data:/app/pb_data
    restart: always

volumes:
  pocketbase_data:
